/**
 * Ask · compiler — the ONLY place a model is called for the Ask feature.
 *
 * Single non-streaming messages.create with a closed tool catalog and
 * `tool_choice: any` (refusal is itself a tool). The model's entire job is to
 * pick one intent and fill its parameters from the server-provided
 * vocabulary; the returned tool call is schema-validated here before any
 * executor sees it. Numbers are never generated by the model.
 */

import Anthropic from '@anthropic-ai/sdk';
import logger from '../../utils/logger';

// Sonnet is the default; ASK_MODEL exists as the documented cheap-mode /
// upgrade knob (e.g. a Haiku-class model) without a deploy.
function askModel(): string {
  return process.env.ASK_MODEL ?? 'claude-sonnet-5';
}

const MAX_TOKENS = 600;

// Frozen — never interpolate per-request data into the system prompt.
const SYSTEM_PROMPT =
  'You translate one analytics question about a tournament into exactly one tool call. ' +
  'Fill parameters ONLY with values from the provided vocabulary. ' +
  'If the question is off-topic, about other events, or unanswerable with the available tools, call refuse.';

// ── Client (optional — same pattern as ReportAgent) ────────────────────────

let client: Anthropic | null | undefined;

function getClient(): Anthropic | null {
  if (client === undefined) {
    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (apiKey) {
      client = new Anthropic({ apiKey });
    } else {
      client = null;
      logger.warn('[Ask] ANTHROPIC_API_KEY not set — Ask feature disabled');
    }
  }
  return client;
}

/** True when an API key is configured; the route 501s otherwise. */
export function isAskConfigured(): boolean {
  return getClient() !== null;
}

// ── Manual schema validation ────────────────────────────────────────────────
//
// The tool schemas are plain JSON-schema objects (no `strict` field), so the
// API does not guarantee the input validates. We check the subset of JSON
// schema the catalog actually uses: object shape, required keys, primitive
// types, enum membership, array items and min/max bounds. Unknown extra keys
// are stripped rather than rejected — a hallucinated sibling key should not
// torpedo an otherwise valid intent.

interface PropSchema {
  type?: string;
  enum?: unknown[];
  items?: PropSchema;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
}

function validateValue(value: unknown, schema: PropSchema, path: string): string | null {
  if (schema.enum && !schema.enum.includes(value)) {
    return `${path}: not in the allowed values`;
  }
  switch (schema.type) {
    case 'string':
      if (typeof value !== 'string') return `${path}: expected string`;
      break;
    case 'boolean':
      if (typeof value !== 'boolean') return `${path}: expected boolean`;
      break;
    case 'integer':
      if (typeof value !== 'number' || !Number.isInteger(value)) return `${path}: expected integer`;
      if (schema.minimum !== undefined && value < schema.minimum) return `${path}: below minimum`;
      if (schema.maximum !== undefined && value > schema.maximum) return `${path}: above maximum`;
      break;
    case 'number':
      if (typeof value !== 'number') return `${path}: expected number`;
      break;
    case 'array': {
      if (!Array.isArray(value)) return `${path}: expected array`;
      if (schema.minItems !== undefined && value.length < schema.minItems) return `${path}: too few items`;
      if (schema.maxItems !== undefined && value.length > schema.maxItems) return `${path}: too many items`;
      if (schema.items) {
        for (let i = 0; i < value.length; i++) {
          const err = validateValue(value[i], schema.items, `${path}[${i}]`);
          if (err) return err;
        }
      }
      break;
    }
    default:
      break;
  }
  return null;
}

/**
 * Validate a tool_use input against the catalog schema. Returns the cleaned
 * params (unknown keys stripped) or an error string.
 */
function validateInput(
  input: unknown,
  schema: Anthropic.Tool.InputSchema,
): { params: Record<string, unknown> } | { error: string } {
  if (typeof input !== 'object' || input === null || Array.isArray(input)) {
    return { error: 'input is not an object' };
  }
  const properties = (schema.properties ?? {}) as Record<string, PropSchema>;
  const required = (schema as { required?: string[] }).required ?? [];
  const raw = input as Record<string, unknown>;
  const params: Record<string, unknown> = {};

  for (const key of required) {
    if (raw[key] === undefined || raw[key] === null) {
      return { error: `missing required parameter "${key}"` };
    }
  }
  for (const [key, value] of Object.entries(raw)) {
    const propSchema = properties[key];
    if (!propSchema) continue; // strip unknown keys
    if (value === undefined || value === null) continue;
    const err = validateValue(value, propSchema, key);
    if (err) return { error: err };
    params[key] = value;
  }
  return { params };
}

// ── Compile ─────────────────────────────────────────────────────────────────

export interface CompiledIntent {
  name: string;
  input: Record<string, unknown>;
}

/** Fallback intent when the model output is unusable — never throw to users. */
function refuseIntent(message: string): CompiledIntent {
  return { name: 'refuse', input: { reason: 'unsupported', message } };
}

/**
 * One model call: vocabulary + view state + question in, exactly one
 * validated tool call out. Validation failures degrade to a `refuse` intent.
 */
export async function compileIntent(opts: {
  tools: Anthropic.Tool[];
  context: string;
  question: string;
}): Promise<CompiledIntent> {
  const anthropic = getClient();
  if (!anthropic) {
    throw new Error('Ask is not configured');
  }

  const response = await anthropic.messages.create({
    model: askModel(),
    max_tokens: MAX_TOKENS,
    system: SYSTEM_PROMPT,
    tools: opts.tools,
    tool_choice: { type: 'any' },
    messages: [
      {
        role: 'user',
        content: `${opts.context}\n\nQUESTION: ${opts.question}`,
      },
    ],
  });

  const toolUse = response.content.find(
    (block): block is Anthropic.ToolUseBlock => block.type === 'tool_use',
  );
  if (!toolUse) {
    logger.warn('[Ask] Model returned no tool call', { stopReason: response.stop_reason });
    return refuseIntent('I could not turn that into a question this page can answer.');
  }

  const tool = opts.tools.find((t) => t.name === toolUse.name);
  if (!tool) {
    logger.warn('[Ask] Model called a tool outside the catalog', { name: toolUse.name });
    return refuseIntent('I could not turn that into a question this page can answer.');
  }

  const validated = validateInput(toolUse.input, tool.input_schema);
  if ('error' in validated) {
    logger.warn('[Ask] Tool call failed validation', { name: toolUse.name, error: validated.error });
    return refuseIntent('I understood the question but could not resolve it against this series — try rephrasing.');
  }

  return { name: toolUse.name, input: validated.params };
}
